export const ROUTES = {
  home: '/',
  auth: {
    login: '/auth/login',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  admin: {
    dashboard: '/admin/panel',
    home: '/admin/inicio',
    contacts: '/admin/contactos',
    contactSettings: '/admin/contactos/configuracion',
    categories: '/admin/categorias',
    newCategory: '/admin/categorias/nueva',
    editCategory: (id: string) => `/admin/categorias/${id}/editar` as const,
    categoryGallery: (id: string) => `/admin/categorias/${id}/galeria` as const,
    services: '/admin/servicios',
    newService: '/admin/servicios/nuevo',
    testimonials: '/admin/testimonios',
    editTestimonial: (id: string) => `/admin/testimonios/${id}/editar` as const,
    about: '/admin/sobre-mi',
    settings: '/admin/configuracion',
    siteSettings: '/admin/configuracion/sitio',
    theme: '/admin/tema',
    analytics: '/admin/analitica',
    calendar: '/admin/calendario',
    calendarEdit: (id: string) => `/admin/calendario/${id}/editar` as const,
    account: '/admin/mi-cuenta',
    help: '/admin/ayuda',
    trash: '/admin/papelera',
  },
  public: {
    about: '/sobre-mi',
    portfolio: '/portfolio',
    services: '/servicios',
    serviceDetail: (slug: string) => `/servicios/${slug}` as const,
    contact: '/contacto',
    privacy: '/privacidad',
  },
} as const
