// Expanded emoji categories for IconPicker
export const EMOJI_CATEGORIES: Record<string, string[]> = {
  'Maquillaje y Belleza': [
    '💄', '💋', '👄', '💅', '✨', '🌟', '⭐', '💫', '🎀', '🎗️',
    '👁️', '👀', '🦋', '🌸', '🌺', '🌹', '🌷', '💐', '🌻', '🌼',
    '💎', '💍', '🩷', '💜', '💖', '💝', '💗', '💓', '💞', '💕',
    '🪞', '🛁', '🧴', '🧼', '🪥', '💊', '🧪', '🩺', '🌙', '☀️',
    '🎭', '🎪', '🩷', '🩶', '🫦', '👸', '🧖', '🧘', '💆', '💇',
  ],
  Profesional: [
    '📸', '🎬', '🎥', '📹', '🎭', '🎨', '🖌️', '✏️', '📝', '📋',
    '💼', '🏆', '🎯', '📊', '📈', '✅', '⚡', '🔥', '💡', '🎓',
    '🤝', '👋', '👍', '👏', '💪', '🙌', '✌️', '🤟', '🖐️', '👆',
    '🏅', '🥇', '🎖️', '📣', '📢', '🔔', '🔕', '📌', '📍', '🗺️',
    '⚡', '🚀', '💼', '🗂️', '📐', '📏', '🖊️', '🖋️', '📒', '📓',
  ],
  Comunicación: [
    '📧', '📩', '✉️', '📨', '📬', '📭', '📮', '📪', '📫', '💬',
    '💭', '🗨️', '🗯️', '📞', '📱', '📲', '☎️', '🌐', '🔗', '📍',
    '🗣️', '👥', '👤', '🤳', '💌', '📮', '🔔', '📡', '📻', '📺',
  ],
  Social: [
    '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '😊',
    '😍', '🥰', '😘', '🤩', '😎', '🥳', '🎉', '🎊', '🎁', '🎈',
    '🤗', '😇', '🥲', '🫶', '🫂', '💟', '♥️', '💯', '🎀', '🌈',
    '🌍', '🌎', '🌏', '✌️', '👊', '🤜', '🤛', '🙏', '🫱', '🫲',
  ],
  Navegación: [
    '🏠', '🏡', '🏢', '📁', '📂', '📰', '📄', '📃', '📑', '🔖',
    '🔍', '🔎', '⚙️', '🔧', '🔨', '🛠️', '🔐', '🔒', '🔓', '🔑',
    '↗️', '↘️', '↙️', '↖️', '⬆️', '⬇️', '➡️', '⬅️', '↩️', '↪️',
    '🔄', '🔃', '↕️', '↔️', '⏩', '⏪', '⏫', '⏬', '⏯️', '▶️',
    '⏹️', '⏺️', '🔀', '🔁', '🔂', '🆕', '🆗', '🆙', '🆒', '🆓',
  ],
  'Arte y Creatividad': [
    '🎨', '🖼️', '🖌️', '🎭', '🎪', '🎠', '🎡', '🎢', '🎯', '🎲',
    '🧵', '🧶', '👗', '👠', '👡', '👢', '👒', '🎩', '👑', '💐',
    '🎸', '🎹', '🎺', '🎻', '🥁', '🎷', '🎼', '🎵', '🎶', '🎤',
    '🖊️', '✒️', '🖋️', '🖍️', '✏️', '📐', '📏', '🗃️', '🗄️', '🗑️',
  ],
  'Tiempo y Calendario': [
    '📅', '📆', '🗓️', '⏰', '⏱️', '⏲️', '🕐', '🕑', '🕒', '🕓',
    '🌅', '🌄', '🌇', '🌆', '🌃', '🌙', '🌚', '🌝', '🌞', '☀️',
    '🕰️', '⌚', '⏳', '⌛', '🕛', '🕧', '🕐', '🕜', '🕑', '🕝',
  ],
  Naturaleza: [
    '🌸', '🌺', '🌹', '🌷', '🌻', '🌼', '💐', '🍀', '🌿', '🍃',
    '🌱', '🌲', '🌳', '🌴', '🌵', '🍂', '🍁', '🍄', '🌾', '🪻',
    '🌊', '🏔️', '⛰️', '🌋', '🏝️', '🌅', '🌈', '❄️', '🌬️', '🌪️',
    '🦚', '🦜', '🦋', '🐝', '🌺', '🍓', '🍇', '🍑', '🍒', '🌮',
  ],
  'Estilo y Moda': [
    '👗', '👘', '👙', '🩱', '🩲', '🩳', '👚', '👕', '👔', '🧥',
    '🥻', '🩴', '👠', '👡', '👢', '👞', '👟', '🥿', '🧤', '🧣',
    '👒', '🎩', '🧢', '⛑️', '👑', '💍', '💎', '👛', '👜', '🎒',
    '🪮', '💄', '🕶️', '🥽', '🦺', '🧳', '🧲', '📿', '🧸', '🪆',
  ],
  'Comida y Bienestar': [
    '🍵', '☕', '🧋', '🍹', '🥤', '🍷', '🥂', '🍾', '🫖', '🍫',
    '🍰', '🎂', '🧁', '🍩', '🍪', '🍓', '🫐', '🍑', '🥑', '🫚',
    '💊', '🧴', '🧼', '🛁', '🛀', '🧘', '🏋️', '🤸', '🧗', '🏃',
    '🌿', '🍃', '🌱', '🪴', '🎍', '🪷', '🌾', '🫧', '💧', '🌊',
  ],
  Celebración: [
    '🎉', '🎊', '🎁', '🎈', '🥳', '🎆', '🎇', '🎋', '🎍', '🎎',
    '🎏', '🎐', '🎑', '🧧', '🎀', '🎗️', '🎟️', '🎫', '🏮', '🪔',
    '🕯️', '🎄', '🎃', '🎆', '✨', '💥', '🌟', '⭐', '🌠', '🎑',
  ],
  Viajes: [
    '✈️', '🚀', '🛸', '🚁', '🛩️', '🚂', '🚃', '🚄', '🚅', '🚆',
    '🚇', '🚈', '🚉', '🚊', '🚋', '🚌', '🚍', '🚎', '🚐', '🚑',
    '🗺️', '🧭', '🏔️', '🏝️', '🗼', '🗽', '🗿', '🏰', '🏯', '⛩️',
    '🌍', '🌎', '🌏', '🧳', '🎫', '🎟️', '🎡', '🎢', '🎠', '🎪',
  ],
}

// Curated Lucide icon names for a beauty/portfolio context
// Format: [iconName, category]
export const LUCIDE_ICON_LIST: [string, string][] = [
  // Photography
  ['Camera', 'Fotografía'],
  ['CameraOff', 'Fotografía'],
  ['Image', 'Fotografía'],
  ['Images', 'Fotografía'],
  ['ImagePlus', 'Fotografía'],
  ['Video', 'Fotografía'],
  ['Film', 'Fotografía'],
  ['Aperture', 'Fotografía'],
  ['Focus', 'Fotografía'],
  ['Scan', 'Fotografía'],
  // Communication
  ['Mail', 'Comunicación'],
  ['MailOpen', 'Comunicación'],
  ['MessageCircle', 'Comunicación'],
  ['MessageSquare', 'Comunicación'],
  ['Phone', 'Comunicación'],
  ['PhoneCall', 'Comunicación'],
  ['Send', 'Comunicación'],
  ['Inbox', 'Comunicación'],
  ['Bell', 'Comunicación'],
  ['BellRing', 'Comunicación'],
  ['AtSign', 'Comunicación'],
  ['Globe', 'Comunicación'],
  ['Link', 'Comunicación'],
  ['Share2', 'Comunicación'],
  ['Rss', 'Comunicación'],
  // Social
  ['Heart', 'Social'],
  ['HeartHandshake', 'Social'],
  ['Star', 'Social'],
  ['Sparkles', 'Social'],
  ['ThumbsUp', 'Social'],
  ['Users', 'Social'],
  ['User', 'Social'],
  ['UserCheck', 'Social'],
  ['UserPlus', 'Social'],
  ['Instagram', 'Social'],
  ['Youtube', 'Social'],
  ['Twitter', 'Social'],
  ['Linkedin', 'Social'],
  ['Facebook', 'Social'],
  // Art & Creativity
  ['Palette', 'Arte'],
  ['Paintbrush', 'Arte'],
  ['Brush', 'Arte'],
  ['Pencil', 'Arte'],
  ['PenTool', 'Arte'],
  ['Scissors', 'Arte'],
  ['Wand2', 'Arte'],
  ['Wand', 'Arte'],
  ['Layers', 'Arte'],
  ['LayoutGrid', 'Arte'],
  ['Grid', 'Arte'],
  ['Grid3x3', 'Arte'],
  // Professional
  ['Briefcase', 'Profesional'],
  ['Award', 'Profesional'],
  ['Trophy', 'Profesional'],
  ['Medal', 'Profesional'],
  ['Badge', 'Profesional'],
  ['BadgeCheck', 'Profesional'],
  ['Target', 'Profesional'],
  ['Zap', 'Profesional'],
  ['TrendingUp', 'Profesional'],
  ['BarChart2', 'Profesional'],
  ['CheckCircle2', 'Profesional'],
  ['CheckSquare', 'Profesional'],
  ['ClipboardCheck', 'Profesional'],
  ['FileText', 'Profesional'],
  ['FolderOpen', 'Profesional'],
  // Beauty & Wellness
  ['Flower', 'Belleza'],
  ['Flower2', 'Belleza'],
  ['Leaf', 'Belleza'],
  ['Feather', 'Belleza'],
  ['Wind', 'Belleza'],
  ['Droplet', 'Belleza'],
  ['Droplets', 'Belleza'],
  ['Sun', 'Belleza'],
  ['Moon', 'Belleza'],
  ['Stars', 'Belleza'],
  // Navigation & UI
  ['Home', 'Navegación'],
  ['Map', 'Navegación'],
  ['MapPin', 'Navegación'],
  ['Navigation', 'Navegación'],
  ['Compass', 'Navegación'],
  ['Search', 'Navegación'],
  ['ArrowRight', 'Navegación'],
  ['ExternalLink', 'Navegación'],
  ['ChevronRight', 'Navegación'],
  ['ChevronsRight', 'Navegación'],
  // Calendar & Time
  ['Calendar', 'Tiempo'],
  ['CalendarCheck', 'Tiempo'],
  ['CalendarDays', 'Tiempo'],
  ['Clock', 'Tiempo'],
  ['Clock3', 'Tiempo'],
  ['Timer', 'Tiempo'],
  ['Hourglass', 'Tiempo'],
  ['AlarmClock', 'Tiempo'],
]
