// Mapa COMPLETO ISO 3166-1 alpha-2 → nombre en español.
// Fuente: ISO 3166-1 / CLDR es-ES — 249 territorios.
//
// El backend (Vercel GeoIP) es la fuente PRIMARIA de `label`.
// Este mapa es el último recurso de fallback.

// ignore_for_file: prefer_single_quotes
const Map<String, String> _kCountryNames = {
  'AC': 'Isla Ascensión',
  'AD': 'Andorra',
  'AE': 'Emiratos Árabes Unidos',
  'AF': 'Afganistán',
  'AG': 'Antigua y Barbuda',
  'AI': 'Anguila',
  'AL': 'Albania',
  'AM': 'Armenia',
  'AO': 'Angola',
  'AQ': 'Antártida',
  'AR': 'Argentina',
  'AS': 'Samoa Americana',
  'AT': 'Austria',
  'AU': 'Australia',
  'AW': 'Aruba',
  'AX': 'Islas Åland',
  'AZ': 'Azerbaiyán',
  'BA': 'Bosnia y Herzegovina',
  'BB': 'Barbados',
  'BD': 'Bangladés',
  'BE': 'Bélgica',
  'BF': 'Burkina Faso',
  'BG': 'Bulgaria',
  'BH': 'Baréin',
  'BI': 'Burundi',
  'BJ': 'Benín',
  'BL': 'San Bartolomé',
  'BM': 'Bermudas',
  'BN': 'Brunéi',
  'BO': 'Bolivia',
  'BQ': 'Caribe Neerlandés',
  'BR': 'Brasil',
  'BS': 'Bahamas',
  'BT': 'Bután',
  'BV': 'Isla Bouvet',
  'BW': 'Botsuana',
  'BY': 'Bielorrusia',
  'BZ': 'Belice',
  'CA': 'Canadá',
  'CC': 'Islas Cocos',
  'CD': 'República Democrática del Congo',
  'CF': 'República Centroafricana',
  'CG': 'República del Congo',
  'CH': 'Suiza',
  'CI': 'Costa de Marfil',
  'CK': 'Islas Cook',
  'CL': 'Chile',
  'CM': 'Camerún',
  'CN': 'China',
  'CO': 'Colombia',
  'CP': 'Isla Clipperton',
  'CR': 'Costa Rica',
  'CU': 'Cuba',
  'CV': 'Cabo Verde',
  'CW': 'Curazao',
  'CX': 'Isla de Navidad',
  'CY': 'Chipre',
  'CZ': 'Chequia',
  'DE': 'Alemania',
  'DG': 'Diego García',
  'DJ': 'Yibuti',
  'DK': 'Dinamarca',
  'DM': 'Dominica',
  'DO': 'República Dominicana',
  'DZ': 'Argelia',
  'EA': 'Ceuta y Melilla',
  'EC': 'Ecuador',
  'EE': 'Estonia',
  'EG': 'Egipto',
  'EH': 'Sáhara Occidental',
  'ER': 'Eritrea',
  'ES': 'España',
  'ET': 'Etiopía',
  'FI': 'Finlandia',
  'FJ': 'Fiyi',
  'FK': 'Islas Malvinas',
  'FM': 'Micronesia',
  'FO': 'Islas Feroe',
  'FR': 'Francia',
  'GA': 'Gabón',
  'GB': 'Reino Unido',
  'GD': 'Granada (isla)',
  'GE': 'Georgia',
  'GF': 'Guayana Francesa',
  'GG': 'Guernesey',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GL': 'Groenlandia',
  'GM': 'Gambia',
  'GN': 'Guinea',
  'GP': 'Guadalupe',
  'GQ': 'Guinea Ecuatorial',
  'GR': 'Grecia',
  'GS': 'Islas Georgia del Sur y Sandwich del Sur',
  'GT': 'Guatemala',
  'GU': 'Guam',
  'GW': 'Guinea-Bisáu',
  'GY': 'Guyana',
  'HK': 'Hong Kong',
  'HM': 'Islas Heard y McDonald',
  'HN': 'Honduras',
  'HR': 'Croacia',
  'HT': 'Haití',
  'HU': 'Hungría',
  'IC': 'Islas Canarias',
  'ID': 'Indonesia',
  'IE': 'Irlanda',
  'IL': 'Israel',
  'IM': 'Isla de Man',
  'IN': 'India',
  'IO': 'Territorio Británico del Océano Índico',
  'IQ': 'Irak',
  'IR': 'Irán',
  'IS': 'Islandia',
  'IT': 'Italia',
  'JE': 'Jersey',
  'JM': 'Jamaica',
  'JO': 'Jordania',
  'JP': 'Japón',
  'KE': 'Kenia',
  'KG': 'Kirguistán',
  'KH': 'Camboya',
  'KI': 'Kiribati',
  'KM': 'Comoras',
  'KN': 'San Cristóbal y Nieves',
  'KP': 'Corea del Norte',
  'KR': 'Corea del Sur',
  'KW': 'Kuwait',
  'KY': 'Islas Caimán',
  'KZ': 'Kazajistán',
  'LA': 'Laos',
  'LB': 'Líbano',
  'LC': 'Santa Lucía',
  'LI': 'Liechtenstein',
  'LK': 'Sri Lanka',
  'LR': 'Liberia',
  'LS': 'Lesoto',
  'LT': 'Lituania',
  'LU': 'Luxemburgo',
  'LV': 'Letonia',
  'LY': 'Libia',
  'MA': 'Marruecos',
  'MC': 'Mónaco',
  'MD': 'Moldavia',
  'ME': 'Montenegro',
  'MF': 'San Martín (parte francesa)',
  'MG': 'Madagascar',
  'MH': 'Islas Marshall',
  'MK': 'Macedonia del Norte',
  'ML': 'Malí',
  'MM': 'Myanmar (Birmania)',
  'MN': 'Mongolia',
  'MO': 'Macao',
  'MP': 'Islas Marianas del Norte',
  'MQ': 'Martinica',
  'MR': 'Mauritania',
  'MS': 'Montserrat',
  'MT': 'Malta',
  'MU': 'Mauricio',
  'MV': 'Maldivas',
  'MW': 'Malaui',
  'MX': 'México',
  'MY': 'Malasia',
  'MZ': 'Mozambique',
  'NA': 'Namibia',
  'NC': 'Nueva Caledonia',
  'NE': 'Níger',
  'NF': 'Isla Norfolk',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Países Bajos',
  'NO': 'Noruega',
  'NP': 'Nepal',
  'NR': 'Nauru',
  'NU': 'Niue',
  'NZ': 'Nueva Zelanda',
  'OM': 'Omán',
  'PA': 'Panamá',
  'PE': 'Perú',
  'PF': 'Polinesia Francesa',
  'PG': 'Papúa Nueva Guinea',
  'PH': 'Filipinas',
  'PK': 'Pakistán',
  'PL': 'Polonia',
  'PM': 'San Pedro y Miquelón',
  'PN': 'Islas Pitcairn',
  'PR': 'Puerto Rico',
  'PS': 'Territorios Palestinos',
  'PT': 'Portugal',
  'PW': 'Palaos',
  'PY': 'Paraguay',
  'QA': 'Catar',
  'RE': 'Reunión',
  'RO': 'Rumanía',
  'RS': 'Serbia',
  'RU': 'Rusia',
  'RW': 'Ruanda',
  'SA': 'Arabia Saudí',
  'SB': 'Islas Salomón',
  'SC': 'Seychelles',
  'SD': 'Sudán',
  'SE': 'Suecia',
  'SG': 'Singapur',
  'SH': 'Santa Elena',
  'SI': 'Eslovenia',
  'SJ': 'Svalbard y Jan Mayen',
  'SK': 'Eslovaquia',
  'SL': 'Sierra Leona',
  'SM': 'San Marino',
  'SN': 'Senegal',
  'SO': 'Somalia',
  'SR': 'Surinam',
  'SS': 'Sudán del Sur',
  'ST': 'Santo Tomé y Príncipe',
  'SV': 'El Salvador',
  'SX': 'Sint Maarten',
  'SY': 'Siria',
  'SZ': 'Suazilandia',
  'TA': 'Tristán de Acuña',
  'TC': 'Islas Turcas y Caicos',
  'TD': 'Chad',
  'TF': 'Territorios Australes Franceses',
  'TG': 'Togo',
  'TH': 'Tailandia',
  'TJ': 'Tayikistán',
  'TK': 'Tokelau',
  'TL': 'Timor-Leste',
  'TM': 'Turkmenistán',
  'TN': 'Túnez',
  'TO': 'Tonga',
  'TR': 'Turquía',
  'TT': 'Trinidad y Tobago',
  'TV': 'Tuvalu',
  'TW': 'Taiwán',
  'TZ': 'Tanzania',
  'UA': 'Ucrania',
  'UG': 'Uganda',
  'UM': 'Islas Ultramarinas de EE. UU.',
  'US': 'Estados Unidos',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistán',
  'VA': 'Ciudad del Vaticano',
  'VC': 'San Vicente y las Granadinas',
  'VE': 'Venezuela',
  'VG': 'Islas Vírgenes Británicas',
  'VI': 'Islas Vírgenes de EE. UU.',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'WF': 'Wallis y Futuna',
  'WS': 'Samoa',
  'XK': 'Kosovo',
  'YE': 'Yemen',
  'YT': 'Mayotte',
  'ZA': 'Sudáfrica',
  'ZM': 'Zambia',
  'ZW': 'Zimbabue',
};

/// Devuelve el nombre en español del país a partir del código ISO y/o
/// el [label] tal como llega del backend.
///
/// Prioridad:
/// 1. Código ISO en el mapa local (fuente: CLDR es-ES).
/// 2. [label] del backend si ya es legible (>2 chars o contiene espacio).
/// 3. Código en mayúsculas como fallback.
/// 4. 'Desconocido' si no hay nada útil.
String getCountryDisplayName(String? code, String? label) {
  if (code != null && code.isNotEmpty) {
    final upper = code.toUpperCase();
    final mapped = _kCountryNames[upper];
    if (mapped != null) return mapped;
  }

  if (label != null && label.isNotEmpty) {
    final trimmed = label.trim();
    if (trimmed.length > 2 || trimmed.contains(' ')) {
      return _titleCase(trimmed);
    }
    if (trimmed.length == 2) {
      final mapped = _kCountryNames[trimmed.toUpperCase()];
      if (mapped != null) return mapped;
      return trimmed.toUpperCase();
    }
  }

  if (code != null && code.isNotEmpty) return code.toUpperCase();
  return 'Desconocido';
}

/// Convierte a Title Case solo si la cadena está completamente en minúsculas.
String _titleCase(String s) {
  if (s.isEmpty) return s;
  if (s != s.toLowerCase()) return s;
  return s
      .split(' ')
      .map((w) => w.isEmpty ? '' : '${w[0].toUpperCase()}${w.substring(1)}')
      .join(' ');
}
