export const analyticsLogs = [
  {
    eventType: 'page_view',
    pageUrl: '/',
    sessionId: 'seed-session-001',
    device: 'desktop',
    country: 'ES',
    city: 'Granada',
    loadTime: 420,
    scrollDepth: 85,
    timeOnPage: 120,
    utmSource: 'google',
    utmMedium: 'organic',
  },
  {
    eventType: 'page_view',
    pageUrl: '/galeria',
    sessionId: 'seed-session-002',
    device: 'mobile',
    country: 'ES',
    city: 'Madrid',
    loadTime: 680,
    scrollDepth: 60,
    timeOnPage: 95,
  },
  {
    eventType: 'page_view',
    pageUrl: '/contacto',
    sessionId: 'seed-session-003',
    device: 'tablet',
    country: 'ES',
    city: 'Barcelona',
    loadTime: 550,
    scrollDepth: 100,
    timeOnPage: 210,
    referrer: 'https://instagram.com',
  },
  {
    eventType: 'page_view',
    pageUrl: '/servicios',
    sessionId: 'seed-session-004',
    device: 'desktop',
    country: 'MX',
    city: 'Ciudad de Mexico',
    loadTime: 390,
    scrollDepth: 45,
    timeOnPage: 75,
  },
  {
    eventType: 'page_view',
    pageUrl: '/sobre-mi',
    sessionId: 'seed-session-005',
    device: 'desktop',
    country: 'AR',
    city: 'Buenos Aires',
    loadTime: 480,
    scrollDepth: 90,
    timeOnPage: 160,
    utmSource: 'linkedin',
    utmMedium: 'social',
  },
  {
    eventType: 'page_view',
    pageUrl: '/',
    sessionId: 'seed-session-006',
    device: 'mobile',
    country: 'ES',
    city: 'Sevilla',
    loadTime: 310,
    scrollDepth: 65,
    timeOnPage: 85,
    vitalsFCP: 1200,
    vitalsLCP: 2400,
    vitalsCLS: 0.05,
  },
  {
    eventType: 'page_view',
    pageUrl: '/galeria',
    sessionId: 'seed-session-007',
    device: 'desktop',
    country: 'CO',
    city: 'Bogota',
    loadTime: 520,
    scrollDepth: 75,
    timeOnPage: 140,
    utmSource: 'pinterest',
    utmMedium: 'social',
  },
  {
    eventType: 'page_view',
    pageUrl: '/',
    sessionId: 'seed-session-008',
    device: 'mobile',
    country: 'ES',
    city: 'Malaga',
    loadTime: 890,
    scrollDepth: 30,
    timeOnPage: 45,
    vitalsFCP: 2100,
    vitalsLCP: 4500,
    vitalsCLS: 0.25,
    vitalsINP: 180,
  },
  {
    eventType: 'gallery_view',
    entityType: 'category',
    entityId: '78nOaQ4yroN1HfEOxYkT',
    sessionId: 'seed-session-001',
    device: 'desktop',
    country: 'ES',
  },
  {
    eventType: 'gallery_view',
    entityType: 'category',
    entityId: 'VKPLTpOJQWNpOpCN3U1P',
    sessionId: 'seed-session-002',
    device: 'mobile',
    country: 'ES',
    timeOnPage: 45,
  },
  {
    eventType: 'gallery_view',
    entityType: 'category',
    entityId: 'oEEXvBJHvUj0VaGCcILS',
    sessionId: 'seed-session-007',
    device: 'desktop',
    country: 'CO',
  },
  {
    eventType: 'gallery_view',
    entityType: 'category',
    entityId: '78nOaQ4yroN1HfEOxYkT',
    sessionId: 'seed-session-003',
    device: 'tablet',
    country: 'ES',
    timeOnPage: 72,
  },
  {
    eventType: 'contact_submit',
    pageUrl: '/contacto',
    sessionId: 'seed-session-003',
    device: 'tablet',
    country: 'ES',
  },
  {
    eventType: 'contact_submit',
    pageUrl: '/contacto',
    sessionId: 'seed-session-004',
    device: 'desktop',
    country: 'MX',
  },
  {
    eventType: 'click',
    pageUrl: '/',
    clickTarget: 'cta_ver_trabajo',
    sessionId: 'seed-session-001',
    device: 'desktop',
    country: 'ES',
  },
  {
    eventType: 'click',
    pageUrl: '/galeria',
    clickTarget: 'filter_maquillaje',
    sessionId: 'seed-session-002',
    device: 'mobile',
    country: 'ES',
  },
  {
    eventType: 'click',
    pageUrl: '/servicios',
    clickTarget: 'service_fx',
    sessionId: 'seed-session-004',
    device: 'desktop',
    country: 'MX',
  },
  {
    eventType: 'page_view',
    pageUrl: '/',
    sessionId: 'seed-session-009',
    device: 'desktop',
    country: 'US',
    city: 'Miami',
    loadTime: 320,
    timeOnPage: 60,
    utmSource: 'google',
    utmMedium: 'organic',
  },
]
