export const contacts = [
  {
    id: 'seed-contact-1',
    name: 'Elena Rodríguez',
    email: 'elena.rodriguez@example.com',
    phone: '+34 612 345 678',
    message:
      'Hola Paola! Me gustaría consultarte sobre un maquillaje de novia para septiembre. Quiero algo muy natural pero que dure todo el día. ¿Tienes disponibilidad? Un saludo!',
    subject: 'Consulta maquillaje novia',
    responsePreference: 'WHATSAPP',
    status: 'NEW',
    priority: 'HIGH',
    isRead: false,
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'perfil_principal',
  },
  {
    id: 'seed-contact-2',
    name: 'Carlos Méndez',
    email: 'carlos.mendez@example.com',
    phone: '+34 645 789 012',
    message:
      'Buenas tardes, soy director de una obra de teatro independiente en Madrid. Necesitaríamos maquillaje de caracterización para 5 actores para 3 funciones en octubre. ¿Podrías darme un presupuesto aproximado? Gracias.',
    subject: 'Presupuesto para obra de teatro',
    responsePreference: 'EMAIL',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    isRead: true,
    tags: ['teatro', 'presupuesto'],
    adminNote: 'Contactado por teléfono. Pendiente enviar presupuesto detallado.',
  },
  {
    id: 'seed-contact-3',
    name: 'Lucía Fernández',
    email: 'lucia.fernandez@example.com',
    message:
      'Hola! Estoy empezando en el mundo del maquillaje FX y me encantaría saber si ofreces algún tipo de curso o mentoría. Tu trabajo es increíble!',
    subject: 'Consulta sobre mentoría',
    responsePreference: 'EMAIL',
    status: 'REPLIED',
    priority: 'LOW',
    isRead: true,
    isReplied: true,
    repliedAt: new Date('2026-05-08'),
    replyText:
      'Hola Lucía! Muchas gracias por tu interés. De momento no tengo cursos programados pero te recomiendo seguirme en Instagram donde a veces comparto tips y tutoriales. Un abrazo!',
    tags: ['mentoría', 'formación'],
  },
  {
    id: 'seed-contact-4',
    name: 'Marina Torres',
    email: 'marina.torres@example.com',
    phone: '+34 698 765 432',
    message:
      'Buenas, quería preguntar si hacéis envíos de posticería a Barcelona. Estoy interesada en un bigote de tul para una producción.',
    subject: 'Envío de posticería',
    responsePreference: 'WHATSAPP',
    status: 'CLOSED',
    priority: 'MEDIUM',
    isRead: true,
    isReplied: true,
    repliedAt: new Date('2026-04-15'),
    tags: ['posticería', 'envío'],
  },
  {
    id: 'seed-contact-5',
    name: 'BUY VIAGRA NOW!!!',
    email: 'spam@pillstore-bogus.ru',
    message: 'Buy cheap pills online! http://spam.example.com',
    status: 'SPAM',
    priority: 'LOW',
    isRead: true,
    tags: ['spam'],
  },
  {
    id: 'seed-contact-6',
    name: 'Alejandra Soto',
    email: 'alejandra.soto@example.com',
    phone: '+34 655 123 789',
    message:
      'Hola, vi tu trabajo en Instagram y me encantó. Quería consultar precio para maquillaje de 3 personas para una boda civil en julio. Gracias!',
    subject: 'Maquillaje para boda civil',
    responsePreference: 'WHATSAPP',
    status: 'NEW',
    priority: 'HIGH',
    isRead: false,
    isImportant: true,
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'reels_makeup',
    instagramUser: '@alesoto_',
  },
  {
    id: 'seed-contact-7',
    name: 'Roberto Campos',
    email: 'roberto.campos@example.com',
    phone: '+34 611 444 555',
    message:
      'Buenas Paola, soy productor de un videoclip musical que se grabará en agosto en Granada. Buscamos maquilladora para 2 días de rodaje con varios cambios de look. ¿Me puedes pasar tarifas?',
    subject: 'Presupuesto para videoclip musical',
    responsePreference: 'EMAIL',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    isRead: true,
    isImportant: true,
    tags: ['videoclip', 'presupuesto', 'urgente'],
    adminNote: 'Responder antes del viernes. Posible colaboración con productora conocida.',
  },
]
