// ============================================
// REAL CONTENT DATA - Paola Bolívar Nievas
// ============================================

export const categories = [
  {
    id: '78nOaQ4yroN1HfEOxYkT',
    name: 'Maquillaje',
    slug: 'maquillaje',
    description:
      'Maquillaje profesional para eventos, sesiones fotográficas y producciones audiovisuales',
    coverImageUrl:
      'https://res.cloudinary.com/djlknirsd/image/upload/v1750203132/1000108253_z6pmsq',
    sortOrder: 1,
  },
  {
    id: 'VKPLTpOJQWNpOpCN3U1P',
    name: 'FX',
    slug: 'fx',
    description: 'Efectos especiales, caracterización y prótesis para cine, teatro y eventos',
    coverImageUrl:
      'https://res.cloudinary.com/djlknirsd/image/upload/v1737828564/IMG-20250124-WA0021_blzvja',
    sortOrder: 2,
  },
  {
    id: 'oEEXvBJHvUj0VaGCcILS',
    name: 'Teatro',
    slug: 'teatro',
    description: 'Maquillaje y caracterización para obras teatrales y espectáculos en vivo',
    coverImageUrl:
      'https://res.cloudinary.com/djlknirsd/image/upload/v1750201758/Screenshot_20250618-004339',
    sortOrder: 3,
  },
  {
    id: 'y8Ydk2thZhU3mkNBk9ru',
    name: 'Posticería',
    slug: 'posticeria',
    description: 'Pelucas, bigotes, barbas y postizos capilares hechos a mano',
    coverImageUrl: 'https://res.cloudinary.com/djlknirsd/image/upload/v1738275261/20240216_102147',
    sortOrder: 4,
  },
]

export const services = [
  {
    name: 'Maquillaje de Caracterización',
    slug: 'maquillaje-caracterizacion',
    description:
      'Creación de personajes únicos para cine, teatro y producciones audiovisuales. Incluye diseño, aplicación de prótesis y maquillaje de caracterización completo.',
    shortDesc:
      'Transformación completa para personajes de cine, teatro y TV con prótesis y maquillaje profesional.',
    price: 200,
    priceLabel: 'desde',
    duration: '3-5 horas',
    durationMinutes: 240,
    imageUrl: 'https://res.cloudinary.com/djlknirsd/image/upload/v1737828564/IMG-20250124-WA0058',
    requirements:
      'Llegar con la piel limpia, sin maquillaje previo ni cremas grasas. Traer referencias visuales del personaje si se tienen.',
    cancellationPolicy:
      'Cancelación gratuita hasta 48h antes. Entre 24-48h: 50% del presupuesto. Menos de 24h o no-show: 100%.',
    maxBookingsPerDay: 2,
    advanceNoticeDays: 3,
    isAvailable: true,
    isActive: true,
    isFeatured: true,
    sortOrder: 1,
  },
  {
    name: 'Efectos Especiales (FX)',
    slug: 'efectos-especiales',
    description:
      'Heridas, quemaduras, envejecimiento, zombies y todo tipo de efectos especiales. Materiales profesionales de alta calidad: látex, silicona, gelatina balística.',
    shortDesc:
      'Heridas, prótesis, envejecimiento y FX de alto realismo con materiales profesionales.',
    price: 150,
    priceLabel: 'desde',
    duration: '2-4 horas',
    durationMinutes: 180,
    imageUrl: 'https://res.cloudinary.com/djlknirsd/image/upload/v1737405434/IMG-20241029-WA0036',
    requirements:
      'Informar de alergias a látex, silicona o adhesivos antes de la sesión. Ropa que permita acceso a la zona a maquillar.',
    cancellationPolicy:
      'Cancelación gratuita hasta 48h antes. Entre 24-48h: 50% del presupuesto. Menos de 24h o no-show: 100%.',
    maxBookingsPerDay: 3,
    advanceNoticeDays: 2,
    isAvailable: true,
    isActive: true,
    isFeatured: true,
    sortOrder: 2,
  },
  {
    name: 'Maquillaje para Sesiones Fotográficas',
    slug: 'maquillaje-editorial',
    description:
      'Maquillaje creativo y de tendencia para sesiones fotográficas de moda, publicidad o portfolios. Adaptable al concepto artístico de cada sesión.',
    shortDesc:
      'Maquillaje editorial y de moda para sesiones fotográficas, adaptado al concepto artístico.',
    priceLabel: 'consultar',
    duration: 'Media jornada o jornada completa',
    durationMinutes: 240,
    imageUrl: 'https://res.cloudinary.com/djlknirsd/image/upload/v1750203147/1000108248_ttlkgx',
    requirements:
      'Traer moodboard o referencias del estilo deseado. Piel limpia e hidratada. Prever tiempo extra para cambios de look.',
    cancellationPolicy:
      'Cancelación gratuita hasta 72h antes. Entre 48-72h: 30%. Menos de 48h: 100% por bloqueo de agenda.',
    maxBookingsPerDay: 1,
    advanceNoticeDays: 5,
    isAvailable: true,
    isActive: true,
    isFeatured: true,
    sortOrder: 3,
  },
  {
    name: 'Posticería Profesional',
    slug: 'posticeria-profesional',
    description:
      'Bigotes, barbas, flequillos y pelucas picadas a mano pelo a pelo en tul HD. Uso de pelo natural o kanekalon según necesidad.',
    shortDesc:
      'Postizos capilares artesanales: bigotes, barbas y pelucas picadas a mano en tul HD.',
    price: 80,
    priceLabel: 'desde',
    duration: 'Variable según trabajo',
    imageUrl: 'https://res.cloudinary.com/djlknirsd/image/upload/v1738275261/20240216_081630',
    requirements:
      'Se necesita una prueba previa para toma de medidas y selección de material. Traer foto del personaje o estilo deseado.',
    cancellationPolicy:
      'El 50% del importe se abona al encargar. Cancelación antes de empezar la confección: reembolso completo. Una vez iniciado el trabajo manual: no reembolsable.',
    maxBookingsPerDay: 5,
    advanceNoticeDays: 7,
    isAvailable: true,
    isActive: true,
    isFeatured: false,
    sortOrder: 4,
  },
]

export const testimonials = [
  {
    id: 'testimonial-1',
    name: 'María García',
    text: 'Trabajé con Paola en una producción teatral y su profesionalismo es excepcional. Los maquillajes duraron impecables toda la temporada y cada personaje tenía su propia identidad gracias a su trabajo.',
    excerpt: 'Cada personaje tenía su propia identidad gracias a su trabajo.',
    position: 'Directora de Arte',
    company: 'Teatro Alhambra',
    website: 'https://teatroalhambra.es',
    rating: 5,
    verified: true,
    featured: true,
    status: 'APPROVED',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'testimonial-2',
    name: 'Carlos Ruiz',
    text: 'Contraté a Paola para efectos especiales en mi cortometraje y el resultado superó todas las expectativas. Su creatividad y atención al detalle son impresionantes. Las heridas y el maquillaje de zombie eran hiperrealistas.',
    excerpt: 'Su creatividad y atención al detalle son impresionantes.',
    position: 'Director',
    company: 'Edificio 23 Films',
    email: 'carlos@edificio23.com',
    rating: 5,
    verified: true,
    featured: true,
    status: 'APPROVED',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'testimonial-3',
    name: 'Laura Martínez',
    text: 'He trabajado con Paola en múltiples sesiones fotográficas y siempre aporta ideas geniales. Su técnica es impecable y sabe exactamente cómo adaptarse a diferentes estilos y tendencias.',
    excerpt: 'Siempre aporta ideas geniales. Su técnica es impecable.',
    position: 'Fotógrafa',
    company: 'LM Photography',
    website: 'https://lmphotography.es',
    rating: 5,
    verified: true,
    featured: false,
    status: 'APPROVED',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'testimonial-4',
    name: 'Javier Torres',
    text: 'Increíble el trabajo de posticería. Me hizo un bigote y una barba para una obra de época que parecían completamente reales. Nadie en el público notó que eran postizos. Trabajo artesanal de primer nivel.',
    excerpt: 'Nadie en el público notó que eran postizos. Trabajo artesanal de primer nivel.',
    position: 'Actor',
    company: 'Compañía Nacional de Teatro',
    rating: 5,
    verified: true,
    featured: true,
    status: 'APPROVED',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'testimonial-5',
    name: 'Sofía Ramírez',
    text: 'El maquillaje de novia que me hizo Paola fue exactamente lo que soñaba. Natural, luminoso y duró perfecto desde las 8am hasta la madrugada. Recibí muchísimos cumplidos. Además es un amor de persona.',
    excerpt: 'El maquillaje de novia que soñaba. Duró perfecto todo el día.',
    position: 'Novia',
    email: 'sofia.ramirez@example.com',
    rating: 5,
    verified: true,
    featured: false,
    source: 'instagram',
    status: 'APPROVED',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'testimonial-6',
    name: 'Andrés Molina',
    text: 'Contratamos a Paola para el maquillaje FX de un corto de terror. Creó un envejecimiento de 40 años y varias heridas complejas que en cámara se veían totalmente reales. Profesional, puntual y con un kit de materiales impresionante.',
    excerpt: 'Creó un envejecimiento de 40 años que en cámara se veía totalmente real.',
    position: 'Productor',
    company: 'Black Canvas Studios',
    website: 'https://blackcanvas.studio',
    rating: 5,
    verified: true,
    featured: false,
    status: 'APPROVED',
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'testimonial-7',
    name: 'Clara Vega',
    text: 'Muy buen trabajo de maquillaje editorial. Los tres cambios de look que necesitábamos para el catálogo quedaron espectaculares. Tiene muy buen ojo para el color y la luz. Repetiremos seguro.',
    excerpt: 'Los tres cambios de look quedaron espectaculares. Tiene muy buen ojo.',
    position: 'Estilista de Moda',
    company: 'Freelance',
    rating: 4,
    verified: false,
    featured: false,
    status: 'PENDING',
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 'testimonial-8',
    name: 'Diego Herrera',
    text: 'Un placer trabajar con Paola. Nos salvó una producción de teatro infantil con maquillajes rápidos pero de mucha calidad para 12 niños en tiempo récord. Organizada, paciente y muy creativa con los diseños.',
    excerpt: 'Maquillajes rápidos y de mucha calidad para 12 niños en tiempo récord.',
    position: 'Coordinador',
    company: 'Ayuntamiento de Motril - Cultura',
    email: 'cultura@motril.es',
    rating: 5,
    verified: true,
    featured: false,
    status: 'APPROVED',
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 'testimonial-9',
    name: 'Natalia Orozco',
    text: 'El maquillaje quedó bien pero tuve que esperar 30 minutos de más porque la sesión anterior se alargó. La comunicación previa fue buena y el resultado final me gustó, aunque la espera fue incómoda.',
    excerpt: 'El resultado final me gustó, aunque tuve que esperar 30 minutos de más.',
    rating: 3,
    verified: false,
    featured: false,
    status: 'PENDING',
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 'testimonial-10',
    name: 'Pablo Esteban',
    text: 'Paola me ayudó a diseñar el maquillaje de 5 personajes para mi obra. Cada uno con una personalidad visual completamente distinta. Entendió perfectamente el concepto y lo ejecutó con una precisión increíble. Ya estamos planeando la próxima colaboración.',
    excerpt: 'Entendió perfectamente el concepto y lo ejecutó con precisión increíble.',
    position: 'Dramaturgo y Director',
    company: 'Teatro Independiente Granada',
    rating: 5,
    verified: true,
    featured: true,
    status: 'APPROVED',
    isActive: true,
    sortOrder: 10,
  },
]

export const socialLinks = [
  {
    platform: 'instagram',
    url: 'https://www.instagram.com/paolabolivar.makeup/',
    username: '@paolabolivar.makeup',
    icon: 'Instagram',
    sortOrder: 1,
  },
  {
    platform: 'tiktok',
    url: 'https://tiktok.com/@paolabolivarnievas',
    username: '@paolabolivarnievas',
    icon: 'Music2',
    sortOrder: 2,
  },
  {
    platform: 'youtube',
    url: 'https://youtube.com/@paolabolivarnievas',
    username: '@paolabolivarnievas',
    icon: 'Youtube',
    sortOrder: 3,
  },
  {
    platform: 'linkedin',
    url: 'https://linkedin.com/in/paolabolivarnievas',
    username: 'Paola Bolívar',
    icon: 'Linkedin',
    sortOrder: 4,
  },
  {
    platform: 'facebook',
    url: 'https://facebook.com/paolabolivarnievas',
    username: 'Paola Bolívar Nievas',
    icon: 'Facebook',
    sortOrder: 5,
  },
  {
    platform: 'pinterest',
    url: 'https://pinterest.com/paolabolivarnievas',
    username: '@paolabolivarnievas',
    icon: 'Image',
    sortOrder: 6,
  },
]
